
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD AH AND AX BITS BP BSS BX CALL CLC CLI CMP CMPSB CMPSW CODE COLON COMMA COMMENT CS CX DATA DB DD DEC DIV DL DOT DQ DS DW DX ES HLT IDENTIFIER IDIV IMUL INC INT IP IRET JE JG JL JMP JNE LEA LODSB LODSW LOOP MOV MOVSB MOVSW MUL MULTIPLY NEWLINE NOP NOT NUMBER OR POP PUSH RESB RESD RESQ RESW RET ROL ROR SCASB SCASW SECTION SHL SHR SI SP SS STC STI STOSB STOSW SUB TEST XOR\n    program : statement\n            | program statement\n    \n    statement : expression NEWLINE\n             | expression\n    \n    expression : bits\n               | mov\n    \n    bits : BITS NUMBER\n    \n    registers16 : AX \n                | BX \n                | CX \n                | DX \n                | DL \n                | SP \n                | BP \n                | SI \n                | CS \n                | DS \n                | SS \n                | ES \n                | AH \n                | IP \n    \n    mov : MOV registers16 COMMA NUMBER\n        | MOV registers16 COMMA registers16\n    '
    
_lr_action_items = {'BITS':([0,1,2,3,4,5,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,],[6,6,-1,-4,-5,-6,-2,-3,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-23,-22,]),'MOV':([0,1,2,3,4,5,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,],[7,7,-1,-4,-5,-6,-2,-3,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-23,-22,]),'$end':([1,2,3,4,5,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,],[0,-1,-4,-5,-6,-2,-3,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-23,-22,]),'NEWLINE':([3,4,5,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,],[9,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-23,-22,]),'NUMBER':([6,26,],[10,28,]),'AX':([7,26,],[12,12,]),'BX':([7,26,],[13,13,]),'CX':([7,26,],[14,14,]),'DX':([7,26,],[15,15,]),'DL':([7,26,],[16,16,]),'SP':([7,26,],[17,17,]),'BP':([7,26,],[18,18,]),'SI':([7,26,],[19,19,]),'CS':([7,26,],[20,20,]),'DS':([7,26,],[21,21,]),'SS':([7,26,],[22,22,]),'ES':([7,26,],[23,23,]),'AH':([7,26,],[24,24,]),'IP':([7,26,],[25,25,]),'COMMA':([11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,],[26,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,1,],[2,8,]),'expression':([0,1,],[3,3,]),'bits':([0,1,],[4,4,]),'mov':([0,1,],[5,5,]),'registers16':([7,26,],[11,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','parser.py',16),
  ('program -> program statement','program',2,'p_program','parser.py',17),
  ('statement -> expression NEWLINE','statement',2,'p_statement','parser.py',27),
  ('statement -> expression','statement',1,'p_statement','parser.py',28),
  ('expression -> bits','expression',1,'p_expression','parser.py',35),
  ('expression -> mov','expression',1,'p_expression','parser.py',36),
  ('bits -> BITS NUMBER','bits',2,'p_bits_check','parser.py',49),
  ('registers16 -> AX','registers16',1,'p_registers16','parser.py',58),
  ('registers16 -> BX','registers16',1,'p_registers16','parser.py',59),
  ('registers16 -> CX','registers16',1,'p_registers16','parser.py',60),
  ('registers16 -> DX','registers16',1,'p_registers16','parser.py',61),
  ('registers16 -> DL','registers16',1,'p_registers16','parser.py',62),
  ('registers16 -> SP','registers16',1,'p_registers16','parser.py',63),
  ('registers16 -> BP','registers16',1,'p_registers16','parser.py',64),
  ('registers16 -> SI','registers16',1,'p_registers16','parser.py',65),
  ('registers16 -> CS','registers16',1,'p_registers16','parser.py',66),
  ('registers16 -> DS','registers16',1,'p_registers16','parser.py',67),
  ('registers16 -> SS','registers16',1,'p_registers16','parser.py',68),
  ('registers16 -> ES','registers16',1,'p_registers16','parser.py',69),
  ('registers16 -> AH','registers16',1,'p_registers16','parser.py',70),
  ('registers16 -> IP','registers16',1,'p_registers16','parser.py',71),
  ('mov -> MOV registers16 COMMA NUMBER','mov',4,'p_mov_instruction','parser.py',78),
  ('mov -> MOV registers16 COMMA registers16','mov',4,'p_mov_instruction','parser.py',79),
]
